language: node_js
node_js:
  - 14

cache:
  yarn: true
  directories:
  - node_modules
  - lib/js-ceramic/node_modules
  - lib/js-ceramic/packages/ceramic-common/node_modules
  - lib/js-ceramic/packages/ceramic-core/node_modules
  - lib/js-ceramic/packages/ceramic-cli/node_modules
  - lib/did-jwt-vc/packages/node_modules
  
before_script:
  - yarn run build:deps
  
script:
  - yarn run test
  - yarn run build
  