language: node_js
node_js:
  - 14
cache:
  yarn: true
  directories:
  - node_modules

before_script:
  - npm install -g lerna
script:
  - cd lib/js-ceramic && npm run bootstrap
  - cd lib/js-ceramic && npm run build
  - cd lib/js-ceramic/ceramic-core && yarn link
  - yarn link @ceramicnetwork/ceramic-core
  - yarn run test
  - yarn run build
  